local WeUnitField = {}

function WeUnitField.we_type()
    return 'unit'
end

WeUnitField['TooltipExtended'] = {id = "utub", data_type = 'string'}
WeUnitField['TooltipBasic'] = {id = "utip", data_type = 'string'}
WeUnitField['RequirementsLevels'] = {id = "urqa", data_type = 'string'}
WeUnitField['Requirements'] = {id = "ureq", data_type = 'string'}
WeUnitField['Name'] = {id = "unam", data_type = 'string'}
WeUnitField['Hotkey'] = {id = "uhot", data_type = 'string'}
WeUnitField['Description'] = {id = "ides", data_type = 'string'}
WeUnitField['ButtonPositionY'] = {id = "ubpy", data_type = 'int'}
WeUnitField['ButtonPositionX'] = {id = "ubpx", data_type = 'int'}
WeUnitField['ItemsSold'] = {id = "usei", data_type = 'string'}
WeUnitField['UnitsSold'] = {id = "useu", data_type = 'string'}
WeUnitField['HideMinimapDisplay'] = {id = "uhom", data_type = 'int'}
WeUnitField['UseExtendedLineofSight'] = {id = "ulos", data_type = 'int'}
WeUnitField['UseClickHelper'] = {id = "uuch", data_type = 'int'}
WeUnitField['UpgradesUsed'] = {id = "upgr", data_type = 'string'}
WeUnitField['UnitSoundSet'] = {id = "usnd", data_type = 'string'}
WeUnitField['UnitClassification'] = {id = "utyp", data_type = 'string'}
WeUnitField['MovementType'] = {id = "umvt", data_type = 'string'}
WeUnitField['TurnRate'] = {id = "umvr", data_type = 'unreal'}
WeUnitField['TintingColorBlue'] = {id = "uclb", data_type = 'int'}
WeUnitField['TintingColorGreen'] = {id = "uclg", data_type = 'int'}
WeUnitField['TintingColorRed'] = {id = "uclr", data_type = 'int'}
WeUnitField['Tilesets'] = {id = "util", data_type = 'string'}
WeUnitField['TeamColor'] = {id = "utco", data_type = 'int'}
WeUnitField['TargetedAs'] = {id = "utar", data_type = 'string'}
WeUnitField['Target'] = {id = "utaa", data_type = 'string'}
WeUnitField['ArtTarget'] = {id = "utaa", data_type = 'string'}
WeUnitField['StockStartDelay'] = {id = "usst", data_type = 'int'}
WeUnitField['StockReplenishInterval'] = {id = "usrg", data_type = 'int'}
WeUnitField['StockMaximum'] = {id = "usma", data_type = 'int'}
WeUnitField['SpeedMinimum'] = {id = "umis", data_type = 'int'}
WeUnitField['SpeedMaximum'] = {id = "umas", data_type = 'int'}
WeUnitField['SpeedBase'] = {id = "umvs", data_type = 'int'}
WeUnitField['Special'] = {id = "uspa", data_type = 'string'}
WeUnitField['ArtSpecial'] = {id = "uspa", data_type = 'string'}
WeUnitField['Sleeps'] = {id = "usle", data_type = 'int'}
WeUnitField['SightRadiusNight'] = {id = "usin", data_type = 'int'}
WeUnitField['SightRadiusDay'] = {id = "usid", data_type = 'int'}
WeUnitField['ShadowTextureBuilding'] = {id = "ushb", data_type = 'string'}
WeUnitField['ShadowImageWidth'] = {id = "ushw", data_type = 'real'}
WeUnitField['ShadowImageUnit'] = {id = "ushu", data_type = 'string'}
WeUnitField['ShadowImageHeight'] = {id = "ushh", data_type = 'real'}
WeUnitField['ShadowImageCenterY'] = {id = "ushy", data_type = 'real'}
WeUnitField['ShadowImageCenterX'] = {id = "ushx", data_type = 'real'}
WeUnitField['SelectionScale'] = {id = "ussc", data_type = 'real'}
WeUnitField['SelectionCircleOnWater'] = {id = "usew", data_type = 'int'}
WeUnitField['SelectionCircleHeight'] = {id = "uslz", data_type = 'real'}
WeUnitField['ScalingValue'] = {id = "usca", data_type = 'real'}
WeUnitField['ScaleProjectiles'] = {id = "uscb", data_type = 'int'}
WeUnitField['RequiredBoneNames'] = {id = "ubpr", data_type = 'string'}
WeUnitField['RequiredAttachmentLinkNames'] = {id = "ualp", data_type = 'string'}
WeUnitField['RequiredAnimationNamesAttachments'] = {id = "uaap", data_type = 'string'}
WeUnitField['RequiredAnimationNames'] = {id = "uani", data_type = 'string'}
WeUnitField['RepairTime'] = {id = "urtm", data_type = 'int'}
WeUnitField['RepairLumberCost'] = {id = "ulur", data_type = 'int'}
WeUnitField['RepairGoldCost'] = {id = "ugor", data_type = 'int'}
WeUnitField['RandomSound'] = {id = "ursl", data_type = 'string'}
WeUnitField['Race'] = {id = "urac", data_type = 'string'}
WeUnitField['PropulsionWindowdegrees'] = {id = "uprw", data_type = 'unreal'}
WeUnitField['ProjectileLaunchZSwimming'] = {id = "ulsz", data_type = 'unreal'}
WeUnitField['ProjectileLaunchZ'] = {id = "ulpz", data_type = 'unreal'}
WeUnitField['ProjectileLaunchY'] = {id = "ulpy", data_type = 'unreal'}
WeUnitField['ProjectileLaunchX'] = {id = "ulpx", data_type = 'unreal'}
WeUnitField['ProjectileImpactZSwimming'] = {id = "uisz", data_type = 'unreal'}
WeUnitField['ProjectileImpactZ'] = {id = "uimz", data_type = 'unreal'}
WeUnitField['Priority'] = {id = "upri", data_type = 'int'}
WeUnitField['PointValue'] = {id = "upoi", data_type = 'int'}
WeUnitField['PlaceableInEditor'] = {id = "uine", data_type = 'int'}
WeUnitField['OrientationInterpolation'] = {id = "uori", data_type = 'int'}
WeUnitField['OccluderHeight'] = {id = "uocc", data_type = 'unreal'}
WeUnitField['NormalAbilities'] = {id = "uabi", data_type = 'string'}
WeUnitField['NameEditorSuffix'] = {id = "unsf", data_type = 'string'}
WeUnitField['MovementSound'] = {id = "umsl", data_type = 'string'}
WeUnitField['ModelFileExtraVersions'] = {id = "uver", data_type = 'string'}
WeUnitField['ModelFile'] = {id = "umdl", data_type = 'string'}
WeUnitField['MinimumAttackRange'] = {id = "uamn", data_type = 'int'}
WeUnitField['MaximumRollAngledegrees'] = {id = "umxr", data_type = 'real'}
WeUnitField['MaximumPitchAngledegrees'] = {id = "umxp", data_type = 'real'}
WeUnitField['ManaRegeneration'] = {id = "umpr", data_type = 'unreal'}
WeUnitField['ManaMaximum'] = {id = "umpm", data_type = 'int'}
WeUnitField['ManaInitialAmount'] = {id = "umpi", data_type = 'int'}
WeUnitField['LumberCost'] = {id = "ulum", data_type = 'int'}
WeUnitField['SoundLoopingFadeOutRate'] = {id = "ulfo", data_type = 'int'}
WeUnitField['SoundLoopingFadeInRate'] = {id = "ulfi", data_type = 'int'}
WeUnitField['IsaBuilding'] = {id = "ubdg", data_type = 'int'}
WeUnitField['IconScoreScreen'] = {id = "ussi", data_type = 'string'}
WeUnitField['IconGameInterface'] = {id = "uico", data_type = 'string'}
WeUnitField['HitPointsRegenerationType'] = {id = "uhrt", data_type = 'string'}
WeUnitField['HitPointsRegenerationRate'] = {id = "uhpr", data_type = 'unreal'}
WeUnitField['HitPointsMaximumBase'] = {id = "uhpm", data_type = 'int'}
WeUnitField['MovementHeightMinimum'] = {id = "umvf", data_type = 'unreal'}
WeUnitField['MovementHeight'] = {id = "umvh", data_type = 'unreal'}
WeUnitField['HasWaterShadow'] = {id = "ushr", data_type = 'int'}
WeUnitField['HasTilesetSpecificData'] = {id = "utss", data_type = 'int'}
WeUnitField['GoldCost'] = {id = "ugol", data_type = 'int'}
WeUnitField['GoldBountyAwardedSidesperDie'] = {id = "ubsi", data_type = 'int'}
WeUnitField['GoldBountyAwardedNumberofDice'] = {id = "ubdi", data_type = 'int'}
WeUnitField['GoldBountyAwardedBase'] = {id = "ubba", data_type = 'int'}
WeUnitField['LumberBountyAwardedSidesperDie'] = {id = "ulbs", data_type = 'int'}
WeUnitField['LumberBountyAwardedNumberofDice'] = {id = "ulbd", data_type = 'int'}
WeUnitField['LumberBountyAwardedBase'] = {id = "ulba", data_type = 'int'}
WeUnitField['FoodProduced'] = {id = "ufma", data_type = 'int'}
WeUnitField['FoodCost'] = {id = "ufoo", data_type = 'int'}
WeUnitField['FogOfWarSampleRadius'] = {id = "ufrd", data_type = 'real'}
WeUnitField['ElevationSampleRadius'] = {id = "uerd", data_type = 'real'}
WeUnitField['ElevationSamplePoints'] = {id = "uept", data_type = 'int'}
WeUnitField['DisplayasNeutralHostile'] = {id = "uhos", data_type = 'int'}
WeUnitField['DependencyEquivalents'] = {id = "udep", data_type = 'string'}
WeUnitField['DefenseUpgradeBonus'] = {id = "udup", data_type = 'int'}
WeUnitField['ArmorType'] = {id = "udty", data_type = 'string'}
WeUnitField['DefenseBase'] = {id = "udef", data_type = 'int'}
WeUnitField['DefaultActiveAbility'] = {id = "udaa", data_type = 'string'}
WeUnitField['DeathType'] = {id = "udea", data_type = 'int'}
WeUnitField['DeathTimeseconds'] = {id = "udtm", data_type = 'unreal'}
WeUnitField['CollisionSize'] = {id = "ucol", data_type = 'unreal'}
WeUnitField['CategorizationSpecial'] = {id = "uspe", data_type = 'int'}
WeUnitField['CategorizationCampaign'] = {id = "ucam", data_type = 'int'}
WeUnitField['CanFlee'] = {id = "ufle", data_type = 'int'}
WeUnitField['CanDropItemsOnDeath'] = {id = "udro", data_type = 'int'}
WeUnitField['BuildTime'] = {id = "ubld", data_type = 'int'}
WeUnitField['AttacksEnabled'] = {id = "uaen", data_type = 'int'}
WeUnitField['Attack2WeaponType'] = {id = "ua2w", data_type = 'string'}
WeUnitField['Attack2WeaponSound'] = {id = "ucs2", data_type = 'string'}
WeUnitField['Attack2TargetsAllowed'] = {id = "ua2g", data_type = 'string'}
WeUnitField['Attack2ShowUI'] = {id = "uwu2", data_type = 'int'}
WeUnitField['Attack2RangeMotionBuffer'] = {id = "urb2", data_type = 'unreal'}
WeUnitField['Attack2Range'] = {id = "ua2r", data_type = 'int'}
WeUnitField['Attack2ProjectileSpeed'] = {id = "ua2z", data_type = 'int'}
WeUnitField['Attack2ProjectileHomingEnabled'] = {id = "umh2", data_type = 'int'}
WeUnitField['Attack2ProjectileArt'] = {id = "ua2m", data_type = 'string'}
WeUnitField['Attack2ProjectileArc'] = {id = "uma2", data_type = 'unreal'}
WeUnitField['Attack2MaximumNumberofTargets'] = {id = "utc2", data_type = 'int'}
WeUnitField['Attack2DamageUpgradeAmount'] = {id = "udu2", data_type = 'int'}
WeUnitField['Attack2DamageSpillRadius'] = {id = "usr2", data_type = 'unreal'}
WeUnitField['Attack2DamageSpillDistance'] = {id = "usd2", data_type = 'unreal'}
WeUnitField['Attack2DamageSidesperDie'] = {id = "ua2s", data_type = 'int'}
WeUnitField['Attack2DamageNumberofDice'] = {id = "ua2d", data_type = 'int'}
WeUnitField['Attack2DamageLossFactor'] = {id = "udl2", data_type = 'unreal'}
WeUnitField['Attack2DamageFactorSmall'] = {id = "uqd2", data_type = 'unreal'}
WeUnitField['Attack2DamageFactorMedium'] = {id = "uhd2", data_type = 'unreal'}
WeUnitField['Attack2DamageBase'] = {id = "ua2b", data_type = 'int'}
WeUnitField['Attack2CooldownTime'] = {id = "ua2c", data_type = 'unreal'}
WeUnitField['Attack2AttackType'] = {id = "ua2t", data_type = 'string'}
WeUnitField['Attack2AreaofEffectTargets'] = {id = "ua2p", data_type = 'string'}
WeUnitField['Attack2AreaofEffectSmallDamage'] = {id = "ua2q", data_type = 'int'}
WeUnitField['Attack2AreaofEffectMediumDamage'] = {id = "ua2h", data_type = 'int'}
WeUnitField['Attack2AreaofEffectFullDamage'] = {id = "ua2f", data_type = 'int'}
WeUnitField['Attack2AnimationDamagePoint'] = {id = "udp2", data_type = 'unreal'}
WeUnitField['Attack2AnimationBackswingPoint'] = {id = "ubs2", data_type = 'unreal'}
WeUnitField['Attack2WeaponType'] = {id = "ua1w", data_type = 'string'}
WeUnitField['Attack2WeaponSound'] = {id = "ucs1", data_type = 'string'}
WeUnitField['Attack1TargetsAllowed'] = {id = "ua1g", data_type = 'string'}
WeUnitField['Attack1ShowUI'] = {id = "uwu1", data_type = 'int'}
WeUnitField['Attack1RangeMotionBuffer'] = {id = "urb1", data_type = 'unreal'}
WeUnitField['Attack1Range'] = {id = "ua1r", data_type = 'int'}
WeUnitField['Attack1ProjectileSpeed'] = {id = "ua1z", data_type = 'int'}
WeUnitField['Attack1ProjectileHomingEnabled'] = {id = "umh1", data_type = 'int'}
WeUnitField['Attack1ProjectileArt'] = {id = "ua1m", data_type = 'string'}
WeUnitField['Attack1ProjectileArc'] = {id = "uma1", data_type = 'unreal'}
WeUnitField['Attack1MaximumNumberofTargets'] = {id = "utc1", data_type = 'int'}
WeUnitField['Attack1DamageUpgradeAmount'] = {id = "udu1", data_type = 'int'}
WeUnitField['Attack1DamageSpillRadius'] = {id = "usr1", data_type = 'unreal'}
WeUnitField['Attack1DamageSpillDistance'] = {id = "usd1", data_type = 'unreal'}
WeUnitField['Attack1DamageSidesperDie'] = {id = "ua1s", data_type = 'int'}
WeUnitField['Attack1DamageNumberofDice'] = {id = "ua1d", data_type = 'int'}
WeUnitField['Attack1DamageLossFactor'] = {id = "udl1", data_type = 'unreal'}
WeUnitField['Attack1DamageFactorSmall'] = {id = "uqd1", data_type = 'unreal'}
WeUnitField['Attack1DamageFactorMedium'] = {id = "uhd1", data_type = 'unreal'}
WeUnitField['Attack1DamageBase'] = {id = "ua1b", data_type = 'int'}
WeUnitField['Attack1CooldownTime'] = {id = "ua1c", data_type = 'unreal'}
WeUnitField['Attack2AttackType'] = {id = "ua1t", data_type = 'string'}
WeUnitField['Attack1AreaofEffectTargets'] = {id = "ua1p", data_type = 'string'}
WeUnitField['Attack1AreaofEffectSmallDamage'] = {id = "ua1q", data_type = 'int'}
WeUnitField['Attack1AreaofEffectMediumDamage'] = {id = "ua1h", data_type = 'int'}
WeUnitField['Attack1AreaofEffectFullDamage'] = {id = "ua1f", data_type = 'int'}
WeUnitField['Attack1AnimationDamagePoint'] = {id = "udp1", data_type = 'unreal'}
WeUnitField['Attack1AnimationBackswingPoint'] = {id = "ubs1", data_type = 'unreal'}
WeUnitField['ArmorSoundType'] = {id = "uarm", data_type = 'string'}
WeUnitField['AnimationWalkSpeed'] = {id = "uwal", data_type = 'real'}
WeUnitField['AnimationRunSpeed'] = {id = "urun", data_type = 'real'}
WeUnitField['AnimationCastPoint'] = {id = "ucpt", data_type = 'unreal'}
WeUnitField['AnimationCastBackswing'] = {id = "ucbs", data_type = 'unreal'}
WeUnitField['AnimationBlendTimeseconds'] = {id = "uble", data_type = 'real'}
WeUnitField['AllowCustomTeamColor'] = {id = "utcc", data_type = 'int'}
WeUnitField['AIPlacementType'] = {id = "uabt", data_type = 'string'}
WeUnitField['AIPlacementRadius'] = {id = "uabr", data_type = 'unreal'}
WeUnitField['AcquisitionRange'] = {id = "uacq", data_type = 'unreal'}
WeUnitField['TransportedSize'] = {id = "ucar", data_type = 'int'}
WeUnitField['Level'] = {id = "ulev", data_type = 'int'}
WeUnitField['GroupSeparationPriority'] = {id = "urpr", data_type = 'int'}
WeUnitField['GroupSeparationParameter'] = {id = "urpp", data_type = 'int'}
WeUnitField['GroupSeparationGroupNumber'] = {id = "urpg", data_type = 'int'}
WeUnitField['GroupSeparationEnabled'] = {id = "urpo", data_type = 'int'}
WeUnitField['FormationRank'] = {id = "ufor", data_type = 'int'}
WeUnitField['StructuresBuilt'] = {id = "ubui", data_type = 'string'}
WeUnitField['eHeroDeathMsg'] = {id = "uhhd", data_type = 'int'}
WeUnitField['eHeroInterfaceIcon'] = {id = "uhhb", data_type = 'int'}
WeUnitField['eHeroMinimapDisplay'] = {id = "uhhm", data_type = 'int'}
WeUnitField['TooltipRevive'] = {id = "utpr", data_type = 'string'}
WeUnitField['TooltipAwaken'] = {id = "uawt", data_type = 'string'}
WeUnitField['StrengthPerLevel'] = {id = "ustp", data_type = 'unreal'}
WeUnitField['StartingStrength'] = {id = "ustr", data_type = 'int'}
WeUnitField['StartingIntelligence'] = {id = "uint", data_type = 'int'}
WeUnitField['StartingAgility'] = {id = "uagi", data_type = 'int'}
WeUnitField['ProperNamesUsed'] = {id = "upru", data_type = 'int'}
WeUnitField['ProperNames'] = {id = "upro", data_type = 'string'}
WeUnitField['PrimaryAttribute'] = {id = "upra", data_type = 'string'}
WeUnitField['IntelligencePerLevel'] = {id = "uinp", data_type = 'unreal'}
WeUnitField['HeroRevivalLocations'] = {id = "urva", data_type = 'string'}
WeUnitField['HeroAbilities'] = {id = "uhab", data_type = 'string'}
WeUnitField['AgilityPerLevel'] = {id = "uagp", data_type = 'unreal'}
WeUnitField['CasterUpgradeTips'] = {id = "ucut", data_type = 'string'}
WeUnitField['CasterUpgradeNames'] = {id = "ucun", data_type = 'string'}
WeUnitField['CasterUpgradeArt'] = {id = "ucua", data_type = 'string'}
WeUnitField['UpgradesTo'] = {id = "uupt", data_type = 'string'}
WeUnitField['UnitsTrained'] = {id = "utra", data_type = 'string'}
WeUnitField['RevivesDeadHeros'] = {id = "urev", data_type = 'int'}
WeUnitField['ResearchesAvailable'] = {id = "ures", data_type = 'string'}
WeUnitField['PlacementRequiresWaterRadius'] = {id = "upaw", data_type = 'unreal'}
WeUnitField['PlacementRequires'] = {id = "upap", data_type = 'string'}
WeUnitField['PlacementPreventedBy'] = {id = "upar", data_type = 'string'}
WeUnitField['PathingMap'] = {id = "upat", data_type = 'string'}
WeUnitField['NeutralBuildingValidAsRandomBuilding'] = {id = "unbr", data_type = 'int'}
WeUnitField['NeutralBuildingShowsMinimapIcon'] = {id = "unbm", data_type = 'int'}
WeUnitField['ItemsMade'] = {id = "umki", data_type = 'string'}
WeUnitField['GroundTexture'] = {id = "uubs", data_type = 'string'}
WeUnitField['ConstructionSound'] = {id = "ubsl", data_type = 'string'}
WeUnitField["RequierementsForTier1"] = {id = "urq1", data_type = 'string'}
WeUnitField["RequierementsForTier2"] = {id = "urq2", data_type = 'string'}
WeUnitField["RequierementsForTier3"] = {id = "urq3", data_type = 'string'}
WeUnitField["RequierementsForTier4"] = {id = "urq4", data_type = 'string'}
WeUnitField["RequierementsForTier5"] = {id = "urq5", data_type = 'string'}
WeUnitField["RequierementsForTier6"] = {id = "urq6", data_type = 'string'}
WeUnitField["RequierementsForTier7"] = {id = "urq7", data_type = 'string'}
WeUnitField["RequierementsForTier8"] = {id = "urq8", data_type = 'string'}
WeUnitField["RequierementsForTier9"] = {id = "urq9", data_type = 'string'}

return WeUnitField