WeEveryAbilityField = {}
	
WeEveryAbilityField['Name'] = {id = "anam", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['EditorSuffix'] = {id = "ansf", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['HeroAbility'] = {id = "aher", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['ItemAbility'] = {id = "aite", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['Race'] = {id = "arac", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['ButtonPositionNormalX'] = {id = "abpx", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['ButtonPositionNormalY'] = {id = "abpy", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['ButtonPositionTurnOffX'] = {id = "aubx", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['ButtonPositionTurnOffY'] = {id = "auby", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['ButtonPositionResearchX'] = {id = "arpx", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['ButtonPositionResearchY'] = {id = "arpy", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['IconNormal'] = {id = "aart", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['IconTurnOff'] = {id = "auar", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['IconResearch'] = {id = "arar", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['ArtCaster'] = {id = "acat", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['ArtTarget'] = {id = "atat", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['ArtSpecial'] = {id = "asat", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['ArtEffect'] = {id = "aeat", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['AreaEffect'] = {id = "aaea", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['LightningEffects'] = {id = "alig", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['MissileArt'] = {id = "amat", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['MissileSpeed'] = {id = "amsp", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['MissileArc'] = {id = "amac", lvl = 0, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['MissileHomingEnabled'] = {id = "amho", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['TargetAttachments'] = {id = "atac", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['TargetAttachmentPoint'] = {id = "ata0", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TargetAttachmentPoint1'] = {id = "ata1", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TargetAttachmentPoint2'] = {id = "ata2", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TargetAttachmentPoint3'] = {id = "ata3", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TargetAttachmentPoint4'] = {id = "ata4", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TargetAttachmentPoint5'] = {id = "ata5", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['CasterAttachments'] = {id = "acac", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['CasterAttachmentPoint'] = {id = "acap", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['CasterAttachmentPoint1'] = {id = "aca1", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['SpecialAttachmentPoint'] = {id = "aspt", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['AnimationNames'] = {id = "aani", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TooltipNormal'] = {id = "atp1", lvl = -1, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TooltipTurnOff'] = {id = "aut1", lvl = -1, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TooltipNormalExtended'] = {id = "aub1", lvl = -1, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TooltipTurnOffExtended'] = {id = "auu1", lvl = -1, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TooltipLearn'] = {id = "aret", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['TooltipLearnExtended'] = {id = "arut", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['HotkeyLearn'] = {id = "arhk", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['HotkeyNormal'] = {id = "ahky", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['HotkeyTurnOff'] = {id = "auhk", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['Requirements'] = {id = "areq", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['RequirementsLevels'] = {id = "arqa", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['CheckDependencies'] = {id = "achd", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['PriorityforSpellSteal'] = {id = "apri", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['OrderStringUseTurnOn'] = {id = "aord", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['OrderStringTurnOff'] = {id = "aoru", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['OrderStringActivate'] = {id = "aoro", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['OrderStringDeactivate'] = {id = "aorf", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['EffectSound'] = {id = "aefs", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['EffectSoundLooping'] = {id = "aefl", lvl = 0, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['Levels'] = {id = "alev", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['RequiredLevel'] = {id = "arlv", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['LevelSkipRequirement'] = {id = "alsk", lvl = 0, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['TargetsAllowed'] = {id = "atar", lvl = -1, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['CastingTime'] = {id = "acas", lvl = -1, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['DurationNormal'] = {id = "adur", lvl = -1, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['DurationHero'] = {id = "ahdu", lvl = -1, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['Cooldown'] = {id = "acdn", lvl = -1, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['ManaCost'] = {id = "amcs", lvl = -1, abil_data_id = 0, data_type = 'int'}
WeEveryAbilityField['AreaofEffect'] = {id = "aare", lvl = -1, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['CastRange'] = {id = "aran", lvl = -1, abil_data_id = 0, data_type = 'unreal'}
WeEveryAbilityField['Buffs'] = {id = "abuf", lvl = -1, abil_data_id = 0, data_type = 'string'}
WeEveryAbilityField['Effects'] = {id = "aeff", lvl = -1, abil_data_id = 0, data_type = 'string'}

return WeEveryAbilityField